srun: Warning: can't run 1 processes on 10 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 10 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 10 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 10 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 10 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 10 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 10 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 10 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 10 nodes, setting nnodes to 1
srun: Warning: can't run 1 processes on 10 nodes, setting nnodes to 1
3
INFO:brick_stats:entering GetBrickStats...
INFO:brick_stats:CPU_COUNT 32
INFO:brick_stats:sub_surveybricks[0] brickname:1508p015 ra1 150.750000 ra2 151.000000 dec1 1.375000 dec2 1.625000
INFO:brick_stats:sub_surveybricks[3] brickname:1496p017 ra1 149.500000 ra2 149.750000 dec1 1.625000 dec2 1.875000
INFO:brick_stats:sub_surveybricks[1] brickname:1491p017 ra1 149.000000 ra2 149.250000 dec1 1.625000 dec2 1.875000
INFO:brick_stats:sub_surveybricks[4] brickname:1498p017 ra1 149.750000 ra2 150.000000 dec1 1.625000 dec2 1.875000
INFO:brick_stats:sub_surveybricks[2] brickname:1493p017 ra1 149.250000 ra2 149.500000 dec1 1.625000 dec2 1.875000
INFO:brick_stats:sub_surveybricks[5] brickname:1501p017 ra1 150.000000 ra2 150.250000 dec1 1.625000 dec2 1.875000
INFO:brick_stats:sub_surveybricks[6] brickname:1503p017 ra1 150.250000 ra2 150.500000 dec1 1.625000 dec2 1.875000
8
INFO:brick_stats:entering GetBrickStats...
0
INFO:brick_stats:entering GetBrickStats...
INFO:brick_stats:CPU_COUNT 32
INFO:brick_stats:CPU_COUNT 32
INFO:brick_stats:sub_surveybricks[0] brickname:1508p025 ra1 150.750000 ra2 151.000000 dec1 2.375000 dec2 2.625000
INFO:brick_stats:sub_surveybricks[3] brickname:1493p027 ra1 149.250000 ra2 149.500000 dec1 2.625000 dec2 2.875000
INFO:brick_stats:sub_surveybricks[1] brickname:1511p025 ra1 151.000000 ra2 151.250000 dec1 2.375000 dec2 2.625000
INFO:brick_stats:sub_surveybricks[4] brickname:1496p027 ra1 149.500000 ra2 149.750000 dec1 2.625000 dec2 2.875000
INFO:brick_stats:sub_surveybricks[2] brickname:1491p027 ra1 149.000000 ra2 149.250000 dec1 2.625000 dec2 2.875000
INFO:brick_stats:sub_surveybricks[5] brickname:1498p027 ra1 149.750000 ra2 150.000000 dec1 2.625000 dec2 2.875000
INFO:brick_stats:sub_surveybricks[6] brickname:1501p027 ra1 150.000000 ra2 150.250000 dec1 2.625000 dec2 2.875000
INFO:brick_stats:sub_surveybricks[0] brickname:1491p010 ra1 149.000000 ra2 149.250000 dec1 0.875000 dec2 1.125000
INFO:brick_stats:sub_surveybricks[3] brickname:1498p010 ra1 149.750000 ra2 150.000000 dec1 0.875000 dec2 1.125000
INFO:brick_stats:sub_surveybricks[1] brickname:1493p010 ra1 149.250000 ra2 149.500000 dec1 0.875000 dec2 1.125000
INFO:brick_stats:sub_surveybricks[4] brickname:1501p010 ra1 150.000000 ra2 150.250000 dec1 0.875000 dec2 1.125000
INFO:brick_stats:sub_surveybricks[2] brickname:1496p010 ra1 149.500000 ra2 149.750000 dec1 0.875000 dec2 1.125000
INFO:brick_stats:sub_surveybricks[5] brickname:1503p010 ra1 150.250000 ra2 150.500000 dec1 0.875000 dec2 1.125000
INFO:brick_stats:sub_surveybricks[6] brickname:1506p010 ra1 150.500000 ra2 150.750000 dec1 0.875000 dec2 1.125000
6
INFO:brick_stats:entering GetBrickStats...
INFO:brick_stats:CPU_COUNT 32
INFO:brick_stats:sub_surveybricks[0] brickname:1496p022 ra1 149.500000 ra2 149.750000 dec1 2.125000 dec2 2.375000
INFO:brick_stats:sub_surveybricks[3] brickname:1503p022 ra1 150.250000 ra2 150.500000 dec1 2.125000 dec2 2.375000
INFO:brick_stats:sub_surveybricks[1] brickname:1498p022 ra1 149.750000 ra2 150.000000 dec1 2.125000 dec2 2.375000
INFO:brick_stats:sub_surveybricks[4] brickname:1506p022 ra1 150.500000 ra2 150.750000 dec1 2.125000 dec2 2.375000
INFO:brick_stats:sub_surveybricks[2] brickname:1501p022 ra1 150.000000 ra2 150.250000 dec1 2.125000 dec2 2.375000
INFO:brick_stats:sub_surveybricks[5] brickname:1508p022 ra1 150.750000 ra2 151.000000 dec1 2.125000 dec2 2.375000
INFO:brick_stats:sub_surveybricks[6] brickname:1511p022 ra1 151.000000 ra2 151.250000 dec1 2.125000 dec2 2.375000
2
INFO:brick_stats:entering GetBrickStats...
INFO:brick_stats:CPU_COUNT 32
INFO:brick_stats:sub_surveybricks[0] brickname:1491p015 ra1 149.000000 ra2 149.250000 dec1 1.375000 dec2 1.625000
INFO:brick_stats:sub_surveybricks[3] brickname:1498p015 ra1 149.750000 ra2 150.000000 dec1 1.375000 dec2 1.625000
INFO:brick_stats:sub_surveybricks[1] brickname:1493p015 ra1 149.250000 ra2 149.500000 dec1 1.375000 dec2 1.625000
INFO:brick_stats:sub_surveybricks[4] brickname:1501p015 ra1 150.000000 ra2 150.250000 dec1 1.375000 dec2 1.625000
INFO:brick_stats:sub_surveybricks[2] brickname:1496p015 ra1 149.500000 ra2 149.750000 dec1 1.375000 dec2 1.625000
INFO:brick_stats:sub_surveybricks[5] brickname:1503p015 ra1 150.250000 ra2 150.500000 dec1 1.375000 dec2 1.625000
INFO:brick_stats:sub_surveybricks[6] brickname:1506p015 ra1 150.500000 ra2 150.750000 dec1 1.375000 dec2 1.625000
INFO:brick_stats:brick 1496p017 length 130257
INFO:brick_stats:brick 1498p017 length 131062
INFO:brick_stats:brick 1508p015 length 117348
INFO:brick_stats:brick 1501p017 length 130225
INFO:brick_stats:brick 1503p017 length 130334
INFO:brick_stats:brick 1491p017 length 129757
INFO:brick_stats:brick 1493p017 length 130418
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "GetBricksSrc.py", line 75, in GetBrickSrcs
    HDU.writeto(outdir+'brick_%s.fits' % (sub_surveybricks['BRICKNAME'][index]), overwrite = True)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 1603, in writeto
    checksum=checksum)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 879, in writeto
    fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1496p017.fits'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GetBricksSrc.py", line 126, in <module>
    GetBrickStats()
  File "GetBricksSrc.py", line 88, in GetBrickStats
    outputs = p.map(GetBrickSrcs, tasks)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1496p017.fits'
5
INFO:brick_stats:entering GetBrickStats...
INFO:brick_stats:CPU_COUNT 32
INFO:brick_stats:sub_surveybricks[0] brickname:1501p020 ra1 150.000000 ra2 150.250000 dec1 1.875000 dec2 2.125000
INFO:brick_stats:sub_surveybricks[3] brickname:1508p020 ra1 150.750000 ra2 151.000000 dec1 1.875000 dec2 2.125000
INFO:brick_stats:sub_surveybricks[1] brickname:1503p020 ra1 150.250000 ra2 150.500000 dec1 1.875000 dec2 2.125000
INFO:brick_stats:sub_surveybricks[4] brickname:1511p020 ra1 151.000000 ra2 151.250000 dec1 1.875000 dec2 2.125000
INFO:brick_stats:sub_surveybricks[2] brickname:1506p020 ra1 150.500000 ra2 150.750000 dec1 1.875000 dec2 2.125000
INFO:brick_stats:sub_surveybricks[5] brickname:1491p022 ra1 149.000000 ra2 149.250000 dec1 2.125000 dec2 2.375000
INFO:brick_stats:sub_surveybricks[6] brickname:1493p022 ra1 149.250000 ra2 149.500000 dec1 2.125000 dec2 2.375000
4
INFO:brick_stats:entering GetBrickStats...
INFO:brick_stats:CPU_COUNT 32
INFO:brick_stats:sub_surveybricks[0] brickname:1506p017 ra1 150.500000 ra2 150.750000 dec1 1.625000 dec2 1.875000
INFO:brick_stats:sub_surveybricks[3] brickname:1491p020 ra1 149.000000 ra2 149.250000 dec1 1.875000 dec2 2.125000
INFO:brick_stats:sub_surveybricks[1] brickname:1508p017 ra1 150.750000 ra2 151.000000 dec1 1.625000 dec2 1.875000
INFO:brick_stats:sub_surveybricks[4] brickname:1493p020 ra1 149.250000 ra2 149.500000 dec1 1.875000 dec2 2.125000
INFO:brick_stats:sub_surveybricks[2] brickname:1511p017 ra1 151.000000 ra2 151.250000 dec1 1.625000 dec2 1.875000
INFO:brick_stats:sub_surveybricks[5] brickname:1496p020 ra1 149.500000 ra2 149.750000 dec1 1.875000 dec2 2.125000
INFO:brick_stats:sub_surveybricks[6] brickname:1498p020 ra1 149.750000 ra2 150.000000 dec1 1.875000 dec2 2.125000
INFO:brick_stats:brick 1508p025 length 116535
Traceback (most recent call last):
  File "GetBricksSrc.py", line 126, in <module>
    GetBrickStats()
  File "GetBricksSrc.py", line 94, in GetBrickStats
    GetBrickInfoFile()
  File "GetBricksSrc.py", line 98, in GetBrickInfoFile
    f = open(outdir+'brick_list.out',"w")
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_list.out'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "GetBricksSrc.py", line 75, in GetBrickSrcs
    HDU.writeto(outdir+'brick_%s.fits' % (sub_surveybricks['BRICKNAME'][index]), overwrite = True)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 1603, in writeto
    checksum=checksum)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 879, in writeto
    fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1508p025.fits'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GetBricksSrc.py", line 126, in <module>
    GetBrickStats()
  File "GetBricksSrc.py", line 88, in GetBrickStats
    outputs = p.map(GetBrickSrcs, tasks)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1508p025.fits'
7
INFO:brick_stats:entering GetBrickStats...
INFO:brick_stats:CPU_COUNT 32
srun: error: nid00665: task 0: Exited with exit code 1
srun: Terminating job step 28489985.0
INFO:brick_stats:sub_surveybricks[0] brickname:1491p025 ra1 149.000000 ra2 149.250000 dec1 2.375000 dec2 2.625000
INFO:brick_stats:sub_surveybricks[3] brickname:1498p025 ra1 149.750000 ra2 150.000000 dec1 2.375000 dec2 2.625000
INFO:brick_stats:sub_surveybricks[1] brickname:1493p025 ra1 149.250000 ra2 149.500000 dec1 2.375000 dec2 2.625000
INFO:brick_stats:sub_surveybricks[4] brickname:1501p025 ra1 150.000000 ra2 150.250000 dec1 2.375000 dec2 2.625000
INFO:brick_stats:sub_surveybricks[2] brickname:1496p025 ra1 149.500000 ra2 149.750000 dec1 2.375000 dec2 2.625000
INFO:brick_stats:sub_surveybricks[5] brickname:1503p025 ra1 150.250000 ra2 150.500000 dec1 2.375000 dec2 2.625000
INFO:brick_stats:sub_surveybricks[6] brickname:1506p025 ra1 150.500000 ra2 150.750000 dec1 2.375000 dec2 2.625000
INFO:brick_stats:brick 1501p015 length 117479
INFO:brick_stats:brick 1493p015 length 117180
INFO:brick_stats:brick 1498p015 length 117500
INFO:brick_stats:brick 1503p015 length 117455
INFO:brick_stats:brick 1491p015 length 117400
INFO:brick_stats:brick 1496p015 length 116171
INFO:brick_stats:brick 1506p015 length 117326
INFO:brick_stats:brick 1508p022 length 130293
1
INFO:brick_stats:entering GetBrickStats...
INFO:brick_stats:CPU_COUNT 32
INFO:brick_stats:brick 1498p022 length 130111
INFO:brick_stats:sub_surveybricks[0] brickname:1491p012 ra1 149.000000 ra2 149.250000 dec1 1.125000 dec2 1.375000
INFO:brick_stats:sub_surveybricks[3] brickname:1498p012 ra1 149.750000 ra2 150.000000 dec1 1.125000 dec2 1.375000
INFO:brick_stats:sub_surveybricks[1] brickname:1493p012 ra1 149.250000 ra2 149.500000 dec1 1.125000 dec2 1.375000
INFO:brick_stats:sub_surveybricks[4] brickname:1501p012 ra1 150.000000 ra2 150.250000 dec1 1.125000 dec2 1.375000
INFO:brick_stats:sub_surveybricks[2] brickname:1496p012 ra1 149.500000 ra2 149.750000 dec1 1.125000 dec2 1.375000
INFO:brick_stats:sub_surveybricks[5] brickname:1503p012 ra1 150.250000 ra2 150.500000 dec1 1.125000 dec2 1.375000
INFO:brick_stats:sub_surveybricks[6] brickname:1506p012 ra1 150.500000 ra2 150.750000 dec1 1.125000 dec2 1.375000
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "GetBricksSrc.py", line 75, in GetBrickSrcs
    HDU.writeto(outdir+'brick_%s.fits' % (sub_surveybricks['BRICKNAME'][index]), overwrite = True)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 1603, in writeto
    checksum=checksum)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 879, in writeto
    fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1501p015.fits'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GetBricksSrc.py", line 126, in <module>
    GetBrickStats()
  File "GetBricksSrc.py", line 88, in GetBrickStats
    outputs = p.map(GetBrickSrcs, tasks)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1501p015.fits'
INFO:brick_stats:brick 1496p022 length 130847
INFO:brick_stats:brick 1503p022 length 130135
srun: error: nid00666: task 0: Exited with exit code 1
INFO:brick_stats:brick 1506p022 length 129828
srun: Terminating job step 28489985.1
INFO:brick_stats:brick 1501p022 length 129793
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "GetBricksSrc.py", line 75, in GetBrickSrcs
    HDU.writeto(outdir+'brick_%s.fits' % (sub_surveybricks['BRICKNAME'][index]), overwrite = True)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 1603, in writeto
    checksum=checksum)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 879, in writeto
    fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1508p022.fits'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GetBricksSrc.py", line 126, in <module>
    GetBrickStats()
  File "GetBricksSrc.py", line 88, in GetBrickStats
    outputs = p.map(GetBrickSrcs, tasks)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1508p022.fits'
srun: error: nid00667: task 0: Exited with exit code 1
srun: Terminating job step 28489985.2
INFO:brick_stats:brick 1496p020 length 130023
srun: error: nid00668: task 0: Exited with exit code 1
srun: Terminating job step 28489985.3
INFO:brick_stats:brick 1508p020 length 129775
INFO:brick_stats:brick 1493p022 length 129562
INFO:brick_stats:brick 1506p020 length 130370
INFO:brick_stats:brick 1491p022 length 130272
INFO:brick_stats:brick 1501p020 length 129616
INFO:brick_stats:brick 1503p020 length 130188
INFO:brick_stats:brick 1506p017 length 130872
INFO:brick_stats:brick 1498p020 length 129889
INFO:brick_stats:brick 1491p020 length 130246
INFO:brick_stats:brick 1508p017 length 130115
INFO:brick_stats:brick 1493p020 length 130425
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "GetBricksSrc.py", line 75, in GetBrickSrcs
    HDU.writeto(outdir+'brick_%s.fits' % (sub_surveybricks['BRICKNAME'][index]), overwrite = True)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 1603, in writeto
    checksum=checksum)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 879, in writeto
    fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1503p020.fits'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GetBricksSrc.py", line 126, in <module>
    GetBrickStats()
  File "GetBricksSrc.py", line 88, in GetBrickStats
    outputs = p.map(GetBrickSrcs, tasks)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1503p020.fits'
INFO:brick_stats:brick 1496p025 length 117388
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "GetBricksSrc.py", line 75, in GetBrickSrcs
    HDU.writeto(outdir+'brick_%s.fits' % (sub_surveybricks['BRICKNAME'][index]), overwrite = True)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 1603, in writeto
    checksum=checksum)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 879, in writeto
    fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1496p020.fits'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GetBricksSrc.py", line 126, in <module>
    GetBrickStats()
  File "GetBricksSrc.py", line 88, in GetBrickStats
    outputs = p.map(GetBrickSrcs, tasks)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1496p020.fits'
INFO:brick_stats:brick 1491p025 length 117908
srun: error: nid00669: task 0: Exited with exit code 1
srun: Terminating job step 28489985.4
INFO:brick_stats:brick 1498p025 length 116846
INFO:brick_stats:brick 1501p025 length 116618
INFO:brick_stats:brick 1493p025 length 117392
INFO:brick_stats:brick 1506p025 length 118066
INFO:brick_stats:brick 1503p025 length 116975
Traceback (most recent call last):
  File "GetBricksSrc.py", line 126, in <module>
    GetBrickStats()
  File "GetBricksSrc.py", line 94, in GetBrickStats
    GetBrickInfoFile()
  File "GetBricksSrc.py", line 98, in GetBrickInfoFile
    f = open(outdir+'brick_list.out',"w")
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_list.out'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "GetBricksSrc.py", line 75, in GetBrickSrcs
    HDU.writeto(outdir+'brick_%s.fits' % (sub_surveybricks['BRICKNAME'][index]), overwrite = True)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/base.py", line 1603, in writeto
    checksum=checksum)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 879, in writeto
    fileobj = _File(fileobj, mode='ostream', overwrite=overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 150, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/file.py", line 506, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/site-packages/astropy/io/fits/util.py", line 409, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1496p025.fits'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GetBricksSrc.py", line 126, in <module>
    GetBrickStats()
  File "GetBricksSrc.py", line 88, in GetBrickStats
    outputs = p.map(GetBrickSrcs, tasks)
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20180512-1.2.5-img/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_1496p025.fits'
srun: error: nid00672: task 0: Exited with exit code 1
srun: Terminating job step 28489985.7
srun: error: nid00674: task 0: Exited with exit code 1
srun: Terminating job step 28489985.9
srun: error: nid00670: task 0: Exited with exit code 1
srun: Terminating job step 28489985.5
srun: error: nid00671: task 0: Exited with exit code 1
srun: Terminating job step 28489985.6
9
INFO:brick_stats:entering GetBrickStats...
INFO:brick_stats:CPU_COUNT 32
INFO:brick_stats:sub_surveybricks[0] brickname:1503p027 ra1 150.250000 ra2 150.500000 dec1 2.625000 dec2 2.875000
INFO:brick_stats:sub_surveybricks[3] brickname:1511p027 ra1 151.000000 ra2 151.250000 dec1 2.625000 dec2 2.875000
INFO:brick_stats:sub_surveybricks[1] brickname:1506p027 ra1 150.500000 ra2 150.750000 dec1 2.625000 dec2 2.875000
INFO:brick_stats:sub_surveybricks[4] brickname:1493p030 ra1 149.250000 ra2 149.500000 dec1 2.875000 dec2 3.125000
INFO:brick_stats:sub_surveybricks[2] brickname:1508p027 ra1 150.750000 ra2 151.000000 dec1 2.625000 dec2 2.875000
INFO:brick_stats:sub_surveybricks[5] brickname:1496p030 ra1 149.500000 ra2 149.750000 dec1 2.875000 dec2 3.125000
INFO:brick_stats:sub_surveybricks[6] brickname:1498p030 ra1 149.750000 ra2 150.000000 dec1 2.875000 dec2 3.125000
INFO:brick_stats:sub_surveybricks[7] brickname:1501p030 ra1 150.000000 ra2 150.250000 dec1 2.875000 dec2 3.125000
INFO:brick_stats:sub_surveybricks[8] brickname:1503p030 ra1 150.250000 ra2 150.500000 dec1 2.875000 dec2 3.125000
INFO:brick_stats:sub_surveybricks[9] brickname:1506p030 ra1 150.500000 ra2 150.750000 dec1 2.875000 dec2 3.125000
INFO:brick_stats:sub_surveybricks[10] brickname:1508p030 ra1 150.750000 ra2 151.000000 dec1 2.875000 dec2 3.125000
INFO:brick_stats:sub_surveybricks[11] brickname:1495p032 ra1 149.457580 ra2 149.707928 dec1 3.125000 dec2 3.375000
INFO:brick_stats:sub_surveybricks[12] brickname:1498p032 ra1 149.707928 ra2 149.958275 dec1 3.125000 dec2 3.375000
INFO:brick_stats:sub_surveybricks[13] brickname:1500p032 ra1 149.958275 ra2 150.208623 dec1 3.125000 dec2 3.375000
INFO:brick_stats:sub_surveybricks[14] brickname:1503p032 ra1 150.208623 ra2 150.458971 dec1 3.125000 dec2 3.375000
INFO:brick_stats:sub_surveybricks[15] brickname:1505p032 ra1 150.458971 ra2 150.709318 dec1 3.125000 dec2 3.375000
Traceback (most recent call last):
  File "GetBricksSrc.py", line 126, in <module>
    GetBrickStats()
  File "GetBricksSrc.py", line 94, in GetBrickStats
    GetBrickInfoFile()
  File "GetBricksSrc.py", line 98, in GetBrickInfoFile
    f = open(outdir+'brick_list.out',"w")
FileNotFoundError: [Errno 2] No such file or directory: '/global/cscratch1/sd/huikong/Obiwan/dr8/obiwan_out/cosmos_repeat/divided_randoms/brick_list.out'
srun: error: nid00673: task 0: Exited with exit code 1
srun: Terminating job step 28489985.8
